### ISSUE TITLE
Arcane: 13th Arcana (Death) name not displaying

### ISSUE THREAD

**Issue by DeesseFortuna** [AriaSalvatrice/AriaVCVModules#28]
Hey, love your modules!

Just noticed that today's (2020-02-16) Arcana (13) resulted in the card name not being displayed. Wondering if that's intentional or not, or if it's just... unlucky. [Here's the relevant json file.](https://github.com/AriaSalvatrice/Arcane/blob/master/v1/2020-02-16.json)

Not a big deal, initially thought it was part of the slimmed Atout, but it affects Arcane too. At least Arcane shows the art!

Here's a screencap: https://i.imgur.com/iQl4vkJ.gifv and hopefully it's not somehow my fault.

D

**Comment by AriaSalvatrice** [comment]
In Tarot of Marseilles tradition, Death is known as "The arcana without a name". The lack of a label is intentional. 

https://github.com/AriaSalvatrice/AriaVCVModules/blob/master/src/Arcane.cpp#L454

**Comment by DeesseFortuna** [comment]
Seems obvious now. Thanks
