### ISSUE TITLE
Darius an other knob for step but cutting steps from the left

### ISSUE THREAD

**Issue by matthleg** [AriaSalvatrice/AriaVCVModules#32]
Hello, 
I really like darius module and this morning I was thinking it would be nice to have the possibility to begin the sequence not in the first row but in the second or third or fourth... and like this to have already probability at the beginning of the sequence. So maybe a new knob to cut steps from the beginning of the sequence?
Have a nice day and thanks a lot for your great work.
Matthieu

**Comment by AriaSalvatrice** [comment]
A problem with adding a knob to do that - besides my wish to keep this module simple - is that it no longer unambiguously defines where the pattern starts. Using the probability from the previous, disabled step would make sense, but difficult to visually convey.

**Comment by AriaSalvatrice** [comment]
Implemented in the development branch.

![image](https://user-images.githubusercontent.com/25130242/84096892-5d96a900-aa03-11ea-8aa7-4273d2c6d246.png)

**Comment by matthleg** [comment]
Thank a lot
. Very nice.

Le mar. 9 juin 2020 3:43 AM, Aria Salvatrice <notifications@github.com> a
écrit :
