### ISSUE TITLE
Updated Mac Versions

### ISSUE THREAD

**Issue by blackearth2014** [AriaSalvatrice/AriaVCVModules#49]
Aria,

Where can I get the updated Mac version with the Quantizers?

**Comment by AriaSalvatrice** [comment]
Until we can solve the build issues preventing the plugin from being in the official library, interim stable releases are done on the official VCV forums:

https://community.vcvrack.com/t/arias-modules-quatherina-the-quantum-duck-presents-quatherinas-quality-quad-quantizer/10491/4

This version above contains the QQQQ series and Quale, but doesn't contain unstable test modules.

**Comment by blackearth2014** [comment]
Thanks and cool breeze
