### ISSUE TITLE
Make a successor to Darius: how should it work and what should it do?

### ISSUE THREAD

**Issue by AriaSalvatrice** [AriaSalvatrice/AriaVCVModules#8]
Here's a place to dump idle thoughts about how to evolve the Darius sequencer. No promises I'll ever do it. 

My thoughts:

- Darius was made on a whim and should remain exactly as-is, save for voltage range selection. It's meant to inspire and challenge you to work within its limited but easily understood framework.
- None of the requested features are impossible to achieve right now. It takes a bit of patching, and adds negligible sample latency, but it's rather straightforward. My C++ skills are still limited, so no rushing to get it done ASAP.
- Note selection via knob and tooltip is a huge pain, so let's not add note selection to the original Darius - people know how to use quantizers. 
- Just adding every single feature as requested to a new module would mean a super large faceplate and difficult workflow. I want no menu diving. 
- Adding more I/O to the existing 32hp faceplate is impossible, it’d be a separate module no matter what.
- Going past 8 steps means too big a possibility space to program manually (8 steps = 36 nodes, 16 steps = 136 nodes, 16 steps = 528 nodes). If you randomized a pattern this big it’d sound no different from pure randomness, without any discernible repeating pattern.
- The network is currently 1 > 2. 1> 3 would also be possible, but much less intuitive to program. It would also call for separate devices. 
- Things people might want to program:
  - Pitches, quantized or not
  - Chords
  - Note selection from a chord
  - Modulation / general CV
  - Envelopes
  - Gates
- Types of possible motion - adding them all would be silly, which should make the cut?
  - Random, 1 node forward
  - Random, _n_ nodes forward
  - Force a step up or down, 1 node forward
  - Force a step up or down, _n_ nodes forward
  - Same as above but backwards
  - Reset to step 1
  - Jump to node _n_
- Could link multiple instances, similar to Splort and Smerge
- Multiple banks would be good but there's no reason to have a ton of them, since it's all about slowly evolving patterns
- Some features have overlap with other modules I have planned and can share code
- The module should not be named in a way that implies it's superior to the original, nor should it set out to make the original obsolete

----

Excerpts [from the VCV forums](https://community.vcvrack.com/t/aria-salvatrice-signature-series-1-2-0-darius-branching-step-sequencer/7734/):

> CV controls for the route knobs would allow for some compositional subtlety. I’m using a shift register and a comparator so that a note is only played when consecutive notes are different. If I have the top row set mostly the same and the bottom row set all different it would be great to gradually shift the positions of the direction knobs. Thanks. (dag2099)

> Positive/negative voltages (as an add’l option - maybe a few +/- voltage modes in the menu) would be nice. On/off for each step with a probability knob would be cool for a kind of built-in Bernouli gate thing. That, along with a global gate output for triggering envelopes. A built in quantizer with some scales would be neat but not entirely necessary. A global transpose with a CV input (if there were a quantizer built-in with scales, this could transpose the root note). (funkybot)

**Comment by flydoggy** [comment]
Jacks to route triggers to the Randomize CVs and Randomize Routes.  A jack to send CV to select the number of steps.

**Comment by AriaSalvatrice** [comment]
>  it would be nice to have some brench of different length. something like ctrl+click on a knob to turn it into a reset point, (and display it lighter or something) (pyer)

> Might be a good thing to have that Reset Polyphonic. (Coirt)

**Comment by emmahasapetgiraffe** [comment]
i would love to see more playback options. for example not just going forward but going back too, as in reversed order from how its behaving now. right now it goes wider in possibilities from start to the end of the sequence, reversed it would narrow down to 1 note/cv value.
more on playback would be 'play once' meaning play the sequence once on reset.

**Comment by AriaSalvatrice** [comment]
Request for an external random seed in issue linked above.

**Comment by AriaSalvatrice** [comment]
Per #10 , given the recent features added to it, I'm putting the idea of making a successor on standby. Feel free to still comment, plus another developer might want to pick up the idea.
